### ISSUE TITLE
semicolon at the end of the import

### ISSUE THREAD

**Issue by patrinoua** [artsy/icons#22]
We do not use semicolons but when copying an icon we get one

import CheckmarkFillIcon from "@artsy/icons/CheckmarkFillIcon";

Which is removed on save by prettier.

Can we remove it in the first place?

**Comment by dzucconi** [comment]
Sure, feel free to PR!

**Comment by damassi** [comment]
@patrinoua We don't use issues for this stuff -- can you close this and file the JIRA ticket in the Web Practice board? https://artsyproduct.atlassian.net/jira/software/projects/WP/boards/97
